# رابط Google Apps Script للحفظ المستقر
script_url = "https://script.google.com/macros/s/AKfycbxo7RTkPe-brnQwEsRN5C5dOuJ8hfe6q_iCBVpg009mGJ9A7VLy6wIQt4fzBas3Byrt/exec"

# إعدادات الربط بملف جوجل شيت الجديد مع تصاريح الحفظ
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/11osCOW3PLMe5VXGhJzHAAWty4aOiuPjnLRBS3H8bhuA/edit?usp=sharing"
type = "gsheets"

# بيانات اعتماد حساب الخدمة (Service Account) لتمكين الحفظ
project_id = "community-relations"
private_key_id = "8db2a3b4c5d6e7f8g9h0"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7V\n... (تم التشفير للأمان) ...\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-gsheets@community-relations.iam.gserviceaccount.com"
client_id = "12345678901234567890"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheets%40community-relations.iam.gserviceaccount.com"
